apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "druid-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "druid-operator.name" . }}
    helm.sh/chart: {{ include "druid-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

  